/* CREATE SHOP */
export const CREATE_SHOP_START = 'CREATE_SHOP_START';
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS';
export const CREATE_SHOP_FAILURE = 'CREATE_SHOP_FAILURE';

// UPDATE SHOP
export const UPDATE_SHOP_START = 'UPDATE_SHOP_START';
export const UPDATE_SHOP_SUCCESS = 'UPDATE_SHOP_SUCCESS';
export const UPDATE_SHOP_FAILURE = 'UPDATE_SHOP_FAILURE';

/* DELETE SHOP */
export const DELETE_SHOP_START = 'DELETE_SHOP_START';
export const DELETE_SHOP_SUCCESS = 'DELETE_SHOP_SUCCESS';
export const DELETE_SHOP_FAILURE = 'DELETE_SHOP_FAILURE';
